import React, { useState } from "react";
import { AlertTriangle, Camera, CheckCircle2, Sparkles } from "lucide-react";
import { authenticatedFetch, SignInRequiredError } from "../lib/authenticatedFetch";

type Triage = { issue_id:string; suggested_category:string; category_confidence:number; issue_summary:string; reported_symptoms:string[]; visible_observations:string[]; possible_causes:string[]; clarification_questions:string[]; hazard_flags:string[]; urgency:string; required_worker_skills:string[]; customer_confirmation_required:boolean };

export default function AIServiceAdvisor({ onFindWorkers }: { onFindWorkers:(category:string,summary?:string,workflowId?:string,issueId?:string)=>void }) {
  const [problem,setProblem]=useState(""), [images,setImages]=useState<string[]>([]), [workflowId,setWorkflowId]=useState(""), [stage,setStage]=useState("");
  const [result,setResult]=useState<Triage|null>(null), [answers,setAnswers]=useState<Record<string,string>>({}), [correctedCategory,setCorrectedCategory]=useState("");
  const [loading,setLoading]=useState(false), [error,setError]=useState(""), [needsSignIn,setNeedsSignIn]=useState(false);
  const addPhoto=(file?:File)=>{if(!file)return;if(!/image\/(jpeg|png|webp)/.test(file.type)||file.size>5*1024*1024){setError("Use a JPEG, PNG, or WebP photo smaller than 5 MB.");return;}const reader=new FileReader();reader.onload=()=>setImages(old=>[...old,String(reader.result)].slice(0,3));reader.readAsDataURL(file);};
  const analyze=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError("");setNeedsSignIn(false);try{const response=await authenticatedFetch("/api/agents/triage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:problem,images})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Triage failed");setResult(body.triage_result);setWorkflowId(body.workflow_id);setStage(body.current_stage);setCorrectedCategory(body.triage_result.suggested_category);setAnswers({});}catch(e:any){setNeedsSignIn(e instanceof SignInRequiredError);setError(e.message);}finally{setLoading(false);}};
  const clarify=async()=>{if(!result)return;setLoading(true);setError("");try{const response=await authenticatedFetch(`/api/agents/workflows/${workflowId}/clarify`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers,corrected_category:correctedCategory})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Could not update triage");setResult(body.triage_result);setStage(body.current_stage);setCorrectedCategory(body.triage_result.suggested_category);setAnswers({});}catch(e:any){setNeedsSignIn(e instanceof SignInRequiredError);setError(e.message);}finally{setLoading(false);}};
  const confirm=async()=>{if(!result)return;setLoading(true);setError("");try{const response=await authenticatedFetch(`/api/agents/workflows/${workflowId}/confirm`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.detail||"Could not confirm issue");onFindWorkers(correctedCategory||result.suggested_category,result.issue_summary,workflowId,result.issue_id);}catch(e:any){setNeedsSignIn(e instanceof SignInRequiredError);setError(e.message);}finally{setLoading(false);}};
  const checkReview=async()=>{setLoading(true);setError("");try{const response=await authenticatedFetch(`/api/agents/workflows/${workflowId}`);const body=await response.json();if(!response.ok)throw new Error(body.detail||"Could not check review");setStage(body.current_stage);if(body.current_stage==="awaiting_admin_review")setError("The safety review is still open.");}catch(e:any){setNeedsSignIn(e instanceof SignInRequiredError);setError(e.message);}finally{setLoading(false);}};
  if(needsSignIn)return <div className="max-w-xl mx-auto mt-16 p-8 rounded-3xl border bg-white dark:bg-slate-900 text-center"><h1 className="text-xl font-black">Sign-in required</h1><p className="mt-2 text-sm text-gray-500">{error||"Please sign in again to use the AI Advisor."}</p><a href="/" className="inline-block mt-5 px-5 py-3 rounded-xl bg-orange-600 text-white font-bold">Sign in again</a></div>;
  return <div className="max-w-5xl mx-auto space-y-6 pb-16"><header><p className="text-xs font-black uppercase tracking-widest text-orange-600">Triage & vision agent</p><h1 className="text-3xl font-black flex items-center gap-2"><Sparkles className="text-orange-600"/> Describe your problem</h1><p className="text-sm text-gray-500 mt-2">Upload up to three photos. The agent separates what you report from what is actually visible.</p></header><div className="grid lg:grid-cols-2 gap-6">
    <form onSubmit={analyze} className="bg-white dark:bg-slate-900 border dark:border-slate-800 rounded-3xl p-6 space-y-4"><textarea required minLength={5} value={problem} onChange={e=>setProblem(e.target.value)} rows={7} placeholder="Describe symptoms, when they started, and anything unsafe you noticed…" className="w-full p-4 rounded-2xl border dark:border-slate-700 bg-gray-50 dark:bg-slate-800"/><label className="flex items-center justify-center gap-2 p-3 rounded-xl border border-dashed cursor-pointer"><Camera className="w-4 h-4"/> Add photos ({images.length}/3)<input disabled={images.length>=3} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>addPhoto(e.target.files?.[0])}/></label>{images.length>0&&<div className="flex gap-2">{images.map((src,i)=><button type="button" title="Remove photo" onClick={()=>setImages(old=>old.filter((_,index)=>index!==i))} key={i}><img src={src} className="w-20 h-20 rounded-xl object-cover"/></button>)}</div>}<button disabled={loading} className="w-full p-3 rounded-xl bg-orange-600 text-white font-bold">{loading?"Working…":"Analyze text and photos"}</button>{error&&<p className="p-3 rounded-xl bg-rose-50 text-rose-700 text-sm font-bold">{error}</p>}</form>
    {result?<section className="bg-white dark:bg-slate-900 border dark:border-slate-800 rounded-3xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-black text-xl">Structured request</h2><span className="text-xs font-black uppercase text-orange-600">{result.urgency}</span></div><div><p className="text-xs uppercase text-gray-400 font-bold">Suggested category</p><input value={correctedCategory} onChange={e=>setCorrectedCategory(e.target.value)} className="mt-1 w-full p-2 rounded-xl border bg-gray-50 dark:bg-slate-800 font-bold"/><p className="text-xs text-gray-400 mt-1">Confidence {Math.round(result.category_confidence*100)}% · editable by you</p></div><div><p className="text-xs uppercase text-gray-400 font-bold">Summary</p><p className="text-sm">{result.issue_summary}</p></div>{result.visible_observations.length>0&&<Info title="Visible in photos" items={result.visible_observations}/>}<Info title="You reported" items={result.reported_symptoms}/>{result.possible_causes.map((item,i)=><p key={i} className="text-xs p-3 bg-amber-50 text-amber-900 rounded-xl">Possible cause only: {item}</p>)}{result.clarification_questions.length>0&&<div className="space-y-2"><p className="font-bold text-sm">Useful follow-up</p>{result.clarification_questions.map(q=><label key={q} className="block text-xs text-gray-600">{q}<input value={answers[q]||""} onChange={e=>setAnswers(old=>({...old,[q]:e.target.value}))} className="mt-1 w-full p-2 rounded-xl border bg-gray-50 dark:bg-slate-800"/></label>)}<button type="button" disabled={loading||!Object.values(answers).some(Boolean)} onClick={clarify} className="px-4 py-2 rounded-xl bg-stone-800 disabled:bg-gray-300 text-white text-xs font-bold">Update analysis</button></div>}{result.hazard_flags.length>0&&<div className="p-4 bg-rose-50 text-rose-800 rounded-xl"><p className="font-black flex gap-2"><AlertTriangle className="w-5 h-5"/> Safety review required</p><p className="text-xs mt-1">Move away from immediate danger and contact local emergency assistance if needed. Do not wait for an administrator.</p></div>}<button disabled={loading} onClick={stage==="awaiting_admin_review"?checkReview:confirm} className="w-full p-3 rounded-xl bg-emerald-600 disabled:bg-gray-300 text-white font-bold flex justify-center gap-2"><CheckCircle2 className="w-5 h-5"/>{stage==="awaiting_admin_review"?"Check safety review":"Confirm and continue to booking"}</button></section>:<div className="rounded-3xl bg-gray-50 dark:bg-slate-900 grid place-items-center min-h-80 text-sm text-gray-400">Your structured request will appear here.</div>}
  </div></div>;
}

function Info({title,items}:{title:string;items:string[]}){return <div><p className="text-xs uppercase text-gray-400 font-bold">{title}</p>{items.map(item=><p key={item} className="text-sm">• {item}</p>)}</div>}
