import React, { useEffect, useState } from "react";
import { LoaderCircle, MapPin, Search } from "lucide-react";

export interface LocationChoice { label:string; latitude:number; longitude:number; }

export default function LocationSearchInput({value,onChange,onSelect,placeholder="Search area, road or landmark"}:{value:string;onChange:(value:string)=>void;onSelect:(choice:LocationChoice)=>void;placeholder?:string}) {
  const [items,setItems]=useState<LocationChoice[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false);
  useEffect(()=>{if(value.trim().length<3){setItems([]);return;}const timer=setTimeout(async()=>{setLoading(true);try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=pk&addressdetails=1&q=${encodeURIComponent(value)}`,{headers:{"Accept-Language":"en"}});if(response.ok){const body=await response.json();setItems(body.map((item:any)=>({label:item.display_name,latitude:Number(item.lat),longitude:Number(item.lon)})));setOpen(true);}}catch{setItems([]);}finally{setLoading(false);}},500);return()=>clearTimeout(timer);},[value]);
  return <div className="relative"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input value={value} onChange={e=>{onChange(e.target.value);setOpen(true);}} onFocus={()=>setOpen(true)} placeholder={placeholder} autoComplete="off" className="w-full pl-10 pr-10 py-3 rounded-xl bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700"/>{loading&&<LoaderCircle className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 animate-spin text-orange-600"/>}</div>{open&&items.length>0&&<div className="absolute z-[1000] mt-2 w-full bg-white dark:bg-slate-900 border rounded-2xl shadow-2xl overflow-hidden">{items.map(item=><button type="button" key={`${item.latitude}-${item.longitude}`} onClick={()=>{onChange(item.label);onSelect(item);setOpen(false);}} className="w-full p-3 text-left text-xs hover:bg-orange-50 dark:hover:bg-slate-800 flex gap-2 border-b last:border-0"><MapPin className="w-4 h-4 text-orange-600 shrink-0"/><span className="line-clamp-2">{item.label}</span></button>)}</div>}</div>;
}
