import React, { useEffect, useState } from "react";
import { ArrowLeft, Clock3, MapPin, Send, WalletCards } from "lucide-react";
import { auth } from "../lib/firebase";
import { ServiceRequest } from "../types";
import LiveWorkerMap from "./LiveWorkerMap";

export default function WorkerLeadRoom({requestId,onBack}:{requestId:string;onBack:()=>void}){
 const [request,setRequest]=useState<ServiceRequest|null>(null);const [workerPoint,setWorkerPoint]=useState<[number,number]|null>(null);const [price,setPrice]=useState("");const [eta,setEta]=useState("30");const [message,setMessage]=useState("");const [status,setStatus]=useState("");
 useEffect(()=>{(async()=>{const token=await auth.currentUser?.getIdToken();const response=await fetch("/api/requests",{headers:{Authorization:`Bearer ${token}`}});if(response.ok){const list=await response.json();const found=list.find((item:ServiceRequest)=>item.requestId===requestId);setRequest(found||null);setPrice(String(found?.budget||""));}})();navigator.geolocation.getCurrentPosition(pos=>setWorkerPoint([pos.coords.latitude,pos.coords.longitude]));},[requestId]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const token=await auth.currentUser?.getIdToken();const response=await fetch(`/api/requests/${requestId}/bids`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({price:Number(price),etaMinutes:Number(eta),message})});const body=await response.json();setStatus(response.ok?"Your price offer is live. Waiting for the customer to accept.":body.detail||"Bid failed");};
 if(!request)return <div className="py-24 text-center">Loading customer request…</div>;const destination=request.customerLocation;const fakeWorker:any=workerPoint?{uid:auth.currentUser?.uid||"me",name:"Your live position",category:request.serviceCategory,city:"",experience:0,pricing:Number(price)||0,rating:0,reviewCount:0,verified:true,status:"approved",availability:"available",about:"",createdAt:"",location:{latitude:workerPoint[0],longitude:workerPoint[1]},distanceKm:0,matchScore:100}:null;
 return <div className="space-y-5 pb-16"><button onClick={onBack} className="flex gap-2 text-sm font-bold text-gray-500"><ArrowLeft className="w-4 h-4"/>Back to jobs</button><header><span className="text-xs font-black uppercase tracking-widest text-orange-600">Customer is finding a professional</span><h1 className="text-2xl font-black mt-1">{request.title}</h1></header><div className="grid xl:grid-cols-5 gap-5"><section className="xl:col-span-3">{destination?<LiveWorkerMap customer={[destination.latitude,destination.longitude]} workers={fakeWorker?[fakeWorker]:[]} selectedId={fakeWorker?.uid} onSelect={()=>{}}/>:<div className="h-[430px] bg-gray-100 rounded-3xl flex items-center justify-center">Customer location unavailable</div>}</section><form onSubmit={submit} className="xl:col-span-2 p-6 bg-white dark:bg-slate-900 rounded-3xl border space-y-4 h-fit"><div className="p-4 rounded-2xl bg-orange-50"><p className="text-xs text-gray-500">Customer starting budget</p><strong className="text-2xl">Rs. {request.budget.toLocaleString()}</strong></div><p className="text-sm"><MapPin className="inline w-4 h-4 text-orange-500"/> {request.location}</p><div className="p-4 rounded-2xl bg-gray-50 dark:bg-slate-800 text-sm">{request.description}</div><label className="text-xs font-bold block">Your price (PKR)<input required type="number" value={price} onChange={e=>setPrice(e.target.value)} className="mt-2 w-full p-3 rounded-xl border bg-white dark:bg-slate-900"/></label><label className="text-xs font-bold block">Arrival time (minutes)<input required type="number" min="5" value={eta} onChange={e=>setEta(e.target.value)} className="mt-2 w-full p-3 rounded-xl border bg-white dark:bg-slate-900"/></label><label className="text-xs font-bold block">Offer message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Explain what your price includes" className="mt-2 w-full p-3 rounded-xl border bg-white dark:bg-slate-900"/></label>{status&&<p className="p-3 rounded-xl bg-emerald-50 text-emerald-700 text-xs font-bold">{status}</p>}<button className="w-full py-3 rounded-xl bg-orange-600 text-white font-black flex justify-center gap-2"><Send className="w-4 h-4"/>Submit price offer</button><p className="text-[11px] text-gray-500"><Clock3 className="inline w-3 h-3"/> Chat and contact details open after the customer accepts your offer.</p></form></div></div>;
}
